modLoader = "javafml"
loaderVersion = "[34,)"
license = "All Rights Reserved"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
updateJSONURL = "https://raw.githubusercontent.com/Ocelot5836/storage/master/mods/popoutchat/update.json"
authors = "Ocelot"
description = "Adds the ability to pop Minecraft chat out with the click of a button. The chat becomes a separate window with complete support for vanilla chat features."

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "[34,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3,)"
ordering = "NONE"
side = "BOTH"