modLoader = "javafml"
loaderVersion = "[34,)"
license="GPL v3"
issueTrackerURL="https://github.com/Ocelot5836/Pop-Out-Chat/issues"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
updateJSONURL = "https://raw.githubusercontent.com/Ocelot5836/storage/master/mods/popoutchat/update.json"
authors = "Ocelot"
description = "Adds the ability to put the Minecraft chat into its own window with complete Vanilla chat support."

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "[34,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3,)"
ordering = "NONE"
side = "BOTH"